name: reu
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.6
  - numpy
  - scipy
  - scikit-image
  - scikit-learn
  - pandas
  - matplotlib
  - ipython
  - ipywidgets
  - jupyter
  - jupyterlab
  - imageio
  - ffmpeg
